import React from "react";
import Layout from "./../components/Layout";

// Privacy policy points generated by ChatGPT

const Policy = () => {
  return (
    <Layout title={"Privacy Policy"}>
        <div style={{ margin: "1%", marginTop: "2%"}}>
        <h2 className="text-center">Privacy Policy</h2>
          <p>
            We value your privacy and are committed to protecting your personal information. This Privacy Policy outlines how we collect, use, and safeguard your data while you use our platform.
          </p>
          <p><strong>1. Information We Collect</strong></p>
          <p>
            We collect personal information such as your name, email address, shipping details, and payment information to facilitate your shopping experience. We may also gather non-personal information such as browser type and usage statistics for improving the platform.
          </p>
          <p><strong>2. How We Use Your Information</strong></p>
          <p>
            The data we collect is used to process orders, provide customer support, improve our services, and personalize your experience on our website. We may also use your information to send you promotional offers or updates related to your purchases.
          </p>
          <p><strong>3. Sharing Your Information</strong></p>
          <p>
            We do not share your personal data with third parties except when required by law or for the purpose of fulfilling your orders (e.g., payment processors, shipping services).
          </p>
          <p><strong>4. Data Security</strong></p>
          <p>
            We implement robust security measures to protect your personal information from unauthorized access, alteration, or destruction. However, please note that no method of transmission over the internet or electronic storage is 100% secure.
          </p>
          <p><strong>5. Your Rights</strong></p>
          <p>
            You have the right to access, update, or delete your personal information at any time. For any concerns regarding your data or to exercise your rights, please contact us directly.
          </p>
          <p><strong>6. Changes to This Privacy Policy</strong></p>
          <p>
            We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. Any changes will be posted on this page with the updated date.
          </p>
          <p><strong>7. Contact Us</strong></p>
          <p>
            If you have any questions or concerns regarding our Privacy Policy, please reach out to us at https://github.com/cs4218/cs4218-2420-ecom-project-team33.
          </p>
        </div>
    </Layout>
  );
};

export default Policy;
