name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  
jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      
      - name: Install dependencies
        run: npm install
      
      - name: Install client dependencies
        run: |
          cd client
          npm install
      
      - name: Run frontend tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          custom-title: Coverage report for frontend
          working-directory: client
          skip-step: install
          test-script: npm run test
      
      - name: Run backend tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          custom-title: Coverage report for backend
          skip-step: install
          test-script: npm run ci:backend